# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_list', models.ManyToManyField(to='lists.List')),
            ],
        ),
    ]
