# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-28 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_sharedwith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedwith',
            name='shared_list',
        ),
        migrations.DeleteModel(
            name='SharedWith',
        ),
    ]
