# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20200928_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Item')),
            ],
        ),
    ]
