# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='item',
        ),
        migrations.RemoveField(
            model_name='share',
            name='list',
        ),
        migrations.AddField(
            model_name='share',
            name='shared_list',
            field=models.ManyToManyField(to='lists.List'),
        ),
    ]
