# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-29 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0010_auto_20200928_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='shared_list',
        ),
        migrations.AddField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
